### ISSUE TITLE
New CF CertificateManager updates

### ISSUE THREAD

**Issue by 0xMH** [dflook/cloudformation-dns-certificate#11]
Shouldn't we get the README updated and add a new section for the CF CertificateManage updates? 
Since, June 2020 CloudFormation `AWS::CertificateManager::Certificate` allows you to specify the Route53 hosted zone, in which to insert the validation records. 

You can automate the provisioning of ACM certificates with DNS with a single resource. Below you see the required AWS::CertificateManager::Certificate resource:

```
 Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
```
This will create the required DNS validation records for the domain in the specified route53 hosted zone.
